services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432 # default postgres port
      DB_NAME: ${DB_NAME}
      PORT: 4000
    ports:
      - "${PORT}:${PORT}"

